### ISSUE TITLE
Choose the metatags.twig template location

### ISSUE THREAD

**Issue by zomars** [bobdenotter/seo#21]
It would be nice if I could select where to the save metatags template, instead of the theme's default root. Generally I save it into a `/partials` sub-folder.

Thanks for this extension it's super useful.

**Comment by jasperjorna** [comment]
Since I'm using the extension with Bolt 3.\* the `_metatags.twig` is no longer being picked up from the theme folder. Should it be inside a specific folder structure in the theme folder?

**Comment by zomars** [comment]
I've just noticed this also.

**Comment by GwendolenLynch** [comment]
This is due to the template being loaded in the [Twig namespace of `@bolt`](https://github.com/bobdenotter/seo/blob/master/src/SEO.php#L188), which the theme path is very deliberately not included in.

I am presuming this is to prevent them being overridden.

**Comment by jasperjorna** [comment]
@bobdenotter can you clear up what the intention is? The instructions in the README don't seem to apply anymore: https://github.com/bobdenotter/seo#configure-the-meta-tags-output

**Comment by reuhno** [comment]
@bobdenotter Hi, the same for me.. Overwriting _metatags.twig still possible ?

**Comment by flrvt** [comment]
I'm seeing the same behaviour on Bolt 3.0.7 with the dev-master of this extension.

I am pretty sure this is not intentional. @GawainLynch could you elaborate more about the Twig namespace? How can this be fixed? Perhaps I can work on a PR.

**Comment by GwendolenLynch** [comment]
The behaviour isn't Bolt itself so much as the configurable options.

Basically [here](https://github.com/bobdenotter/seo/blob/v0.10.1/config/config.yml.dist#L45) you could add:

``` yaml
# templates:
#     meta: @bolt/_metatags.twig
```

Note that they are probably best left commented out by default, but the example keeping the system default so that if accidentally uncommented it won't break things.

Then [here](https://github.com/bobdenotter/seo/blob/v0.10.1/src/SeoExtension.php#L142):

``` php
protected function getDefaultConfig()
{
    return [
        'templates' => [
            'meta' => '@bolt/_metatags.twig',
        ]
    ];
}
```

Then [here](https://github.com/bobdenotter/seo/blob/v0.10.1/src/SEO.php#L188)

``` php
        $html = $this->app['render']->render($this->config['templates'['meta'], $vars);
```
